language: haskell
sudo: required

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- sudo apt-get update
- sudo add-apt-repository ppa:renemilk/llvm -y
- sudo apt-get update
- sudo apt-get -y install llvm-toolchain-3.7

install:
 - stack setup

script:
 - opt --version
 - stack test

notifications:
 email:
  on_success: false
