name:                multilinear
version:             0.2.2
github:              "ArturB/multilinear"
license:             BSD3
author:              "Artur M. Brodzki"
maintainer:          "artur@brodzki.org"
copyright:           "2018 Artur M. Brodzki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Comprehensive and efficient (multi)linear algebra implementation. 
category:            Machine learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         "Comprehensive and efficient (multi)linear algebra implementation, based on generic tensor formalism and concise Ricci-Curbastro index syntax. More information available on GitHub: <https://github.com/ArturB/multilinear#readme>"

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -O2
- -Wall

default-extensions:
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses

library:
  source-dirs: src
  dependencies:
  - containers >= 0.5
  - deepseq    >= 1.4
  - mwc-random >= 0.13
  - primitive  >= 0.6
  - statistics >= 0.14
  - vector     >= 0.12

tests:
  multilinear-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N  
    dependencies:
    - criterion   >= 1.2
    - deepseq     >= 1.4
    - multilinear

benchmarks:
  multilinear-bench:
    main:                Bench.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion   >= 1.2
    - deepseq     >= 1.4
    - multilinear
